DChat: org.gtdev.dchat.network.ConnMgr Class Reference
org.gtdev.dchat.network.ConnMgr Class Reference
Classes
class Connection
Public Member Functions
ServerSocket makeServerSock (String m_host, int port)
Connection makeConnection (String m_host, int port)
void doBroadcast (MsgPack msg)
void addNewPeer (String uid, Connection c)
void removePeer (String uid)
Connection getPeer (String uid)
Set< String > getPeerlist ()
Static Public Member Functions
static ConnMgr getInstance ()
Public Attributes
Connection.PeerType selfType
String selfUIN = null
Package Attributes
final String TAG = "ConnMgr"
ConcurrentHashMap< String, Connection > PeerList = new ConcurrentHashMap<>()
Private Member Functions
ConnMgr ()
Static Private Attributes
static ConnMgr Instance = null
Detailed Description
Definition at line 19 of file ConnMgr.java.
Constructor & Destructor Documentation
ConnMgr()
org.gtdev.dchat.network.ConnMgr.ConnMgr () inline private
Definition at line 135 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.getInstance().
Member Function Documentation
addNewPeer()
void org.gtdev.dchat.network.ConnMgr.addNewPeer (String uid, Connection c) inline
Definition at line 185 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.PeerList.
Referenced by org.gtdev.dchat.network.functions.LOGIN.feedMsg(), and org.gtdev.dchat.client.ClientLauncher.main().
doBroadcast()
void org.gtdev.dchat.network.ConnMgr.doBroadcast (MsgPack msg) inline
Definition at line 175 of file ConnMgr.java.
References org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.MsgPack.getNetPack(), org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.network.ConnMgr.PeerList, and org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), and org.gtdev.dchat.network.functions.KICK.feedMsg().
getInstance()
static ConnMgr org.gtdev.dchat.network.ConnMgr.getInstance () inline static
Definition at line 137 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.ConnMgr(), and org.gtdev.dchat.network.ConnMgr.Instance.
Referenced by org.gtdev.dchat.network.functions.LIST.feedMsg(), org.gtdev.dchat.network.functions.STATS.feedMsg(), org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.server.ServerLauncher.main(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.recvThread.recvThread(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
getPeer()
Connection org.gtdev.dchat.network.ConnMgr.getPeer (String uid) inline
Definition at line 193 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.PeerList.
Referenced by org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.network.functions.STATS.reply().
getPeerlist()
Set<String> org.gtdev.dchat.network.ConnMgr.getPeerlist () inline
Definition at line 197 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.PeerList.
Referenced by org.gtdev.dchat.network.functions.LIST.reply().
makeConnection()
Connection org.gtdev.dchat.network.ConnMgr.makeConnection (String m_host, int port) inline
Definition at line 163 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
makeServerSock()
ServerSocket org.gtdev.dchat.network.ConnMgr.makeServerSock (String m_host, int port) inline
Definition at line 143 of file ConnMgr.java.
Referenced by org.gtdev.dchat.server.ServerLauncher.main().
removePeer()
void org.gtdev.dchat.network.ConnMgr.removePeer (String uid) inline
Definition at line 189 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.PeerList.
Referenced by org.gtdev.dchat.network.recvThread.run().
Member Data Documentation
Instance
ConnMgr org.gtdev.dchat.network.ConnMgr.Instance = null static private
Definition at line 134 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.getInstance().
PeerList
ConcurrentHashMap<String, Connection> org.gtdev.dchat.network.ConnMgr.PeerList = new ConcurrentHashMap<>() package
Definition at line 131 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.addNewPeer(), org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.network.ConnMgr.getPeer(), org.gtdev.dchat.network.ConnMgr.getPeerlist(), and org.gtdev.dchat.network.ConnMgr.removePeer().
selfType
Connection.PeerType org.gtdev.dchat.network.ConnMgr.selfType
Definition at line 132 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.functions.LIST.feedMsg(), org.gtdev.dchat.network.functions.STATS.feedMsg(), org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.server.ServerLauncher.main(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.network.functions.STATS.reply(), org.gtdev.dchat.network.functions.LIST.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
selfUIN
String org.gtdev.dchat.network.ConnMgr.selfUIN = null
Definition at line 133 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.server.ServerLauncher.main(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), org.gtdev.dchat.network.functions.KICK.reply(), and org.gtdev.dchat.network.recvThread.run().
TAG
final String org.gtdev.dchat.network.ConnMgr.TAG = "ConnMgr" package
Definition at line 130 of file ConnMgr.java.
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/ConnMgr.java