DChat: org.gtdev.dchat.server.ServerLauncher Class Reference
org.gtdev.dchat.server.ServerLauncher Class Reference
Static Public Member Functions
static void main (String[] args)
Static Package Functions
[static initializer]
Static Package Attributes
static String currentDir
static String server_addr = "::"
static int server_port = 9055
static ParametersParser.arg_handler [] defargs
Detailed Description
Definition at line 11 of file ServerLauncher.java.
Member Function Documentation
[static initializer]()
org.gtdev.dchat.server.ServerLauncher.[static initializer] () inline static package
main()
static void org.gtdev.dchat.server.ServerLauncher.main (String [] args) inline static
Definition at line 41 of file ServerLauncher.java.
References org.gtdev.dchat.network.ConnMgr.Connection.PeerType.CLIENT, org.gtdev.dchat.server.ServerLauncher.defargs, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.ConnMgr.makeServerSock(), org.gtdev.dchat.ParametersParser.procArgs(), org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER, org.gtdev.dchat.server.ServerLauncher.server_addr, and org.gtdev.dchat.server.ServerLauncher.server_port.
Member Data Documentation
currentDir
String org.gtdev.dchat.server.ServerLauncher.currentDir static package
Definition at line 13 of file ServerLauncher.java.
defargs
ParametersParser.arg_handler [] org.gtdev.dchat.server.ServerLauncher.defargs static package
Definition at line 15 of file ServerLauncher.java.
Referenced by org.gtdev.dchat.server.ServerLauncher.main().
server_addr
String org.gtdev.dchat.server.ServerLauncher.server_addr = "::" static package
Definition at line 13 of file ServerLauncher.java.
Referenced by org.gtdev.dchat.server.ServerLauncher.main().
server_port
int org.gtdev.dchat.server.ServerLauncher.server_port = 9055 static package
Definition at line 14 of file ServerLauncher.java.
Referenced by org.gtdev.dchat.server.ServerLauncher.main().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/server/ServerLauncher.java