DChat: org.gtdev.dchat.network.functions.BROADCAST Class Reference
org.gtdev.dchat.network.functions.BROADCAST Class Reference
Public Member Functions
void feedMsg (MsgPack fm)
MsgPack reply ()
Package Attributes
Msg from
Detailed Description
Definition at line 10 of file BROADCAST.java.
Member Function Documentation
feedMsg()
void org.gtdev.dchat.network.functions.BROADCAST.feedMsg (MsgPack fm) inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 15 of file BROADCAST.java.
References org.gtdev.dchat.DChatMsg.MsgType.BROADCAST, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.CLIENT, org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.network.functions.BROADCAST.from, org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.network.MsgPack.getConnection(), org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.DChatMsg.Msg.msg_body, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.client.MainUI.msgNotification(), org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER, org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), and org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type().
reply()
MsgPack org.gtdev.dchat.network.functions.BROADCAST.reply () inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 33 of file BROADCAST.java.
Member Data Documentation
from
Msg org.gtdev.dchat.network.functions.BROADCAST.from package
Definition at line 12 of file BROADCAST.java.
Referenced by org.gtdev.dchat.network.functions.BROADCAST.feedMsg().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/functions/BROADCAST.java