DChat: org.gtdev.dchat.network.functions.LIST Class Reference
org.gtdev.dchat.network.functions.LIST Class Reference
Public Member Functions
void feedMsg (MsgPack fm)
MsgPack reply ()
Package Attributes
MsgPack from
Detailed Description
Definition at line 8 of file LIST.java.
Member Function Documentation
feedMsg()
void org.gtdev.dchat.network.functions.LIST.feedMsg (MsgPack fm) inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 13 of file LIST.java.
References org.gtdev.dchat.network.functions.LIST.from, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.ConnMgr.selfType, and org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER.
reply()
MsgPack org.gtdev.dchat.network.functions.LIST.reply () inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 20 of file LIST.java.
References org.gtdev.dchat.network.functions.LIST.from, org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.ConnMgr.getPeerlist(), org.gtdev.dchat.DChatMsg.MsgType.LIST, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER, org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type(), and org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin().
Member Data Documentation
from
MsgPack org.gtdev.dchat.network.functions.LIST.from package
Definition at line 10 of file LIST.java.
Referenced by org.gtdev.dchat.network.functions.LIST.feedMsg(), and org.gtdev.dchat.network.functions.LIST.reply().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/functions/LIST.java