DChat: org.gtdev.dchat.client.MainUI Class Reference
org.gtdev.dchat.client.MainUI Class Reference
Static Public Member Functions
static void createAndShowGUI ()
static void msgNotification (String str)
Package Attributes
JButton sendButton
Static Package Attributes
static JFrame frame
static JTextPane tfChatHistory
static String chatHistory = ""
Private Member Functions
MainUI ()
Detailed Description
Definition at line 15 of file MainUI.java.
Constructor & Destructor Documentation
MainUI()
org.gtdev.dchat.client.MainUI.MainUI () inline private
Definition at line 22 of file MainUI.java.
References org.gtdev.dchat.DChatMsg.MsgType.BROADCAST, org.gtdev.dchat.network.NetPack.fromConnection, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.MsgPack.getNetPack(), org.gtdev.dchat.network.ConnMgr.getPeer(), org.gtdev.dchat.DChatMsg.MsgType.KICK, org.gtdev.dchat.DChatMsg.MsgType.LIST, org.gtdev.dchat.DChatMsg.Msg.msg_body, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.client.MainUI.msgNotification(), org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.client.MainUI.sendButton, org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type(), org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin(), org.gtdev.dchat.DChatMsg.MsgType.STATS, org.gtdev.dchat.DChatMsg.MsgType.STOP, and org.gtdev.dchat.client.MainUI.tfChatHistory.
Referenced by org.gtdev.dchat.client.MainUI.createAndShowGUI().
Member Function Documentation
createAndShowGUI()
static void org.gtdev.dchat.client.MainUI.createAndShowGUI () inline static
Definition at line 142 of file MainUI.java.
References org.gtdev.dchat.client.MainUI.frame, and org.gtdev.dchat.client.MainUI.MainUI().
msgNotification()
static void org.gtdev.dchat.client.MainUI.msgNotification (String str) inline static
Definition at line 155 of file MainUI.java.
References org.gtdev.dchat.client.MainUI.chatHistory, and org.gtdev.dchat.client.MainUI.tfChatHistory.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), and org.gtdev.dchat.client.MainUI.MainUI().
Member Data Documentation
chatHistory
String org.gtdev.dchat.client.MainUI.chatHistory = "" static package
Definition at line 20 of file MainUI.java.
Referenced by org.gtdev.dchat.client.MainUI.msgNotification().
frame
JFrame org.gtdev.dchat.client.MainUI.frame static package
Definition at line 18 of file MainUI.java.
Referenced by org.gtdev.dchat.client.MainUI.createAndShowGUI().
sendButton
JButton org.gtdev.dchat.client.MainUI.sendButton package
Definition at line 17 of file MainUI.java.
Referenced by org.gtdev.dchat.client.MainUI.MainUI().
tfChatHistory
JTextPane org.gtdev.dchat.client.MainUI.tfChatHistory static package
Definition at line 19 of file MainUI.java.
Referenced by org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.client.MainUI.msgNotification().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/client/MainUI.java