DChat: org.gtdev.dchat.network.MsgPack Class Reference
org.gtdev.dchat.network.MsgPack Class Reference
Public Member Functions
MsgPack (NetPack p, ConnMgr.Connection c)
MsgPack (Msg m)
NetPack getNetPack (int type)
MsgPack DealCmd ()
Msg getMessage ()
ConnMgr.Connection getConnection ()
Package Attributes
Msg message
ConnMgr.Connection connection = null
Detailed Description
Definition at line 8 of file MsgPack.java.
Constructor & Destructor Documentation
MsgPack() [1/2]
org.gtdev.dchat.network.MsgPack.MsgPack (NetPack p, ConnMgr.Connection c) inline
Definition at line 13 of file MsgPack.java.
References org.gtdev.dchat.network.NetPack.body, org.gtdev.dchat.network.MsgPack.connection, org.gtdev.dchat.network.MsgPack.message, and org.gtdev.dchat.DChatMsg.Msg.readFrom().
MsgPack() [2/2]
org.gtdev.dchat.network.MsgPack.MsgPack (Msg m) inline
Definition at line 23 of file MsgPack.java.
References org.gtdev.dchat.network.MsgPack.message, org.gtdev.dchat.DChatMsg.Msg.msg_head, and org.gtdev.dchat.DChatMsg.MsgHead.setMsg_time().
Member Function Documentation
DealCmd()
MsgPack org.gtdev.dchat.network.MsgPack.DealCmd () inline
Definition at line 37 of file MsgPack.java.
References org.gtdev.dchat.network.MsgPack.connection, org.gtdev.dchat.DChatMsg.MsgType.convert(), org.gtdev.dchat.network.SvcHandler.feedMsg(), org.gtdev.dchat.network.SvcHandler.EvDispatcher.getHandler(), org.gtdev.dchat.network.MsgPack.message, org.gtdev.dchat.DChatMsg.Msg.msg_body, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, and org.gtdev.dchat.network.SvcHandler.reply().
Referenced by org.gtdev.dchat.network.recvThread.run().
getConnection()
ConnMgr.Connection org.gtdev.dchat.network.MsgPack.getConnection () inline
Definition at line 52 of file MsgPack.java.
References org.gtdev.dchat.network.MsgPack.connection.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), and org.gtdev.dchat.network.functions.LOGIN.feedMsg().
getMessage()
Msg org.gtdev.dchat.network.MsgPack.getMessage () inline
Definition at line 49 of file MsgPack.java.
References org.gtdev.dchat.network.MsgPack.message.
Referenced by org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), org.gtdev.dchat.network.functions.KICK.reply(), and org.gtdev.dchat.network.recvThread.run().
getNetPack()
NetPack org.gtdev.dchat.network.MsgPack.getNetPack (int type) inline
Definition at line 28 of file MsgPack.java.
References org.gtdev.dchat.network.NetPack.body, org.gtdev.dchat.network.NetPack.NetHeader.buildHeader(), org.gtdev.dchat.network.NetPack.header, org.gtdev.dchat.network.MsgPack.message, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, com.qq.tars.protocol.tars.TarsOutputStream.toByteArray(), and org.gtdev.dchat.DChatMsg.Msg.writeTo().
Referenced by org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.network.recvThread.run().
Member Data Documentation
connection
ConnMgr.Connection org.gtdev.dchat.network.MsgPack.connection = null package
Definition at line 11 of file MsgPack.java.
Referenced by org.gtdev.dchat.network.MsgPack.DealCmd(), org.gtdev.dchat.network.MsgPack.getConnection(), and org.gtdev.dchat.network.MsgPack.MsgPack().
message
Msg org.gtdev.dchat.network.MsgPack.message package
Definition at line 10 of file MsgPack.java.
Referenced by org.gtdev.dchat.network.MsgPack.DealCmd(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.MsgPack.getNetPack(), and org.gtdev.dchat.network.MsgPack.MsgPack().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/MsgPack.java