DChat: org.gtdev.dchat.DChatMsg.MsgHead Class Reference
org.gtdev.dchat.DChatMsg.MsgHead Class Reference
Public Member Functions
String getFrom_uin ()
void setFrom_uin (String from_uin)
String getTo_uin ()
void setTo_uin (String to_uin)
int getMsg_type ()
void setMsg_type (int msg_type)
long getMsg_seq ()
void setMsg_seq (long msg_seq)
long getMsg_time ()
void setMsg_time (long msg_time)
MsgHead ()
MsgHead (String from_uin, String to_uin, int msg_type, long msg_seq, long msg_time)
int hashCode ()
boolean equals (Object obj)
void writeTo (TarsOutputStream _os)
void readFrom (TarsInputStream _is)
Public Member Functions inherited from com.qq.tars.protocol.tars.TarsStructBase
abstract void writeTo (TarsOutputStream os)
abstract void readFrom (TarsInputStream is)
void display (StringBuilder sb, int level)
void displaySimple (StringBuilder sb, int level)
TarsStructBase newInit ()
void recyle ()
boolean containField (String name)
Object getFieldByName (String name)
void setFieldByName (String name, Object value)
byte [] toByteArray ()
byte [] toByteArray (String encoding)
String toString ()
Public Attributes
String from_uin = ""
String to_uin = ""
int msg_type = 0
long msg_seq = 0L
long msg_time = 0L
Additional Inherited Members
Static Public Member Functions inherited from com.qq.tars.protocol.tars.TarsStructBase
static String toDisplaySimpleString (TarsStructBase struct)
Static Public Attributes inherited from com.qq.tars.protocol.tars.TarsStructBase
static final byte BYTE = 0
static final byte SHORT = 1
static final byte INT = 2
static final byte LONG = 3
static final byte FLOAT = 4
static final byte DOUBLE = 5
static final byte STRING1 = 6
static final byte STRING4 = 7
static final byte MAP = 8
static final byte LIST = 9
static final byte STRUCT_BEGIN = 10
static final byte STRUCT_END = 11
static final byte ZERO_TAG = 12
static final byte SIMPLE_LIST = 13
static final int MAX_STRING_LENGTH = 100 * 1024 * 1024
Detailed Description
Definition at line 14 of file MsgHead.java.
Constructor & Destructor Documentation
MsgHead() [1/2]
org.gtdev.dchat.DChatMsg.MsgHead.MsgHead () inline
Definition at line 67 of file MsgHead.java.
Referenced by org.gtdev.dchat.DChatMsg.MsgHead.equals().
MsgHead() [2/2]
org.gtdev.dchat.DChatMsg.MsgHead.MsgHead (String from_uin, String to_uin, int msg_type, long msg_seq, long msg_time) inline
Definition at line 70 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.DChatMsg.MsgHead.msg_time, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, and org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
Member Function Documentation
equals()
boolean org.gtdev.dchat.DChatMsg.MsgHead.equals (Object obj) inline
Definition at line 91 of file MsgHead.java.
References com.qq.tars.protocol.tars.TarsUtil.equals(), org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.DChatMsg.MsgHead.msg_time, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), and org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
getFrom_uin()
String org.gtdev.dchat.DChatMsg.MsgHead.getFrom_uin () inline
Definition at line 27 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.from_uin.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), and org.gtdev.dchat.network.functions.KICK.feedMsg().
getMsg_seq()
long org.gtdev.dchat.DChatMsg.MsgHead.getMsg_seq () inline
Definition at line 51 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_seq.
getMsg_time()
long org.gtdev.dchat.DChatMsg.MsgHead.getMsg_time () inline
Definition at line 59 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_time.
getMsg_type()
int org.gtdev.dchat.DChatMsg.MsgHead.getMsg_type () inline
Definition at line 43 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_type.
getTo_uin()
String org.gtdev.dchat.DChatMsg.MsgHead.getTo_uin () inline
Definition at line 35 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
hashCode()
int org.gtdev.dchat.DChatMsg.MsgHead.hashCode () inline
Definition at line 79 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.from_uin, com.qq.tars.protocol.tars.TarsUtil.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.DChatMsg.MsgHead.msg_time, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, and org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
readFrom()
void org.gtdev.dchat.DChatMsg.MsgHead.readFrom (TarsInputStream _is) inline
Definition at line 120 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.DChatMsg.MsgHead.msg_time, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, com.qq.tars.protocol.tars.TarsInputStream.read(), and com.qq.tars.protocol.tars.TarsInputStream.readString().
setFrom_uin()
void org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin (String from_uin) inline
Definition at line 31 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.from_uin.
Referenced by org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
setMsg_seq()
void org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq (long msg_seq) inline
Definition at line 55 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_seq.
Referenced by org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
setMsg_time()
void org.gtdev.dchat.DChatMsg.MsgHead.setMsg_time (long msg_time) inline
Definition at line 63 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_time.
Referenced by org.gtdev.dchat.network.MsgPack.MsgPack().
setMsg_type()
void org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type (int msg_type) inline
Definition at line 47 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.msg_type.
Referenced by org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
setTo_uin()
void org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin (String to_uin) inline
Definition at line 39 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
Referenced by org.gtdev.dchat.client.ClientLauncher.main(), org.gtdev.dchat.client.MainUI.MainUI(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), and org.gtdev.dchat.network.functions.KICK.reply().
writeTo()
void org.gtdev.dchat.DChatMsg.MsgHead.writeTo (TarsOutputStream _os) inline
Definition at line 111 of file MsgHead.java.
References org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.DChatMsg.MsgHead.msg_time, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, org.gtdev.dchat.DChatMsg.MsgHead.to_uin, and com.qq.tars.protocol.tars.TarsOutputStream.write().
Member Data Documentation
from_uin
String org.gtdev.dchat.DChatMsg.MsgHead.from_uin = ""
Definition at line 17 of file MsgHead.java.
Referenced by org.gtdev.dchat.DChatMsg.MsgHead.equals(), org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.DChatMsg.MsgHead.getFrom_uin(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.STATS.reply(), org.gtdev.dchat.network.functions.KICK.reply(), org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
msg_seq
long org.gtdev.dchat.DChatMsg.MsgHead.msg_seq = 0L
Definition at line 23 of file MsgHead.java.
Referenced by org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.DChatMsg.MsgHead.equals(), org.gtdev.dchat.DChatMsg.MsgHead.getMsg_seq(), org.gtdev.dchat.network.MsgPack.getNetPack(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), org.gtdev.dchat.DChatMsg.MsgHead.readFrom(), org.gtdev.dchat.network.functions.STATS.reply(), org.gtdev.dchat.network.functions.LIST.reply(), org.gtdev.dchat.network.functions.KICK.reply(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
msg_time
long org.gtdev.dchat.DChatMsg.MsgHead.msg_time = 0L
Definition at line 25 of file MsgHead.java.
Referenced by org.gtdev.dchat.DChatMsg.MsgHead.equals(), org.gtdev.dchat.DChatMsg.MsgHead.getMsg_time(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), org.gtdev.dchat.DChatMsg.MsgHead.readFrom(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_time(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
msg_type
int org.gtdev.dchat.DChatMsg.MsgHead.msg_type = 0
Definition at line 21 of file MsgHead.java.
Referenced by org.gtdev.dchat.network.MsgPack.DealCmd(), org.gtdev.dchat.DChatMsg.MsgHead.equals(), org.gtdev.dchat.network.functions.STOP.feedMsg(), org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.DChatMsg.MsgHead.getMsg_type(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), org.gtdev.dchat.DChatMsg.MsgHead.readFrom(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
to_uin
String org.gtdev.dchat.DChatMsg.MsgHead.to_uin = ""
Definition at line 19 of file MsgHead.java.
Referenced by org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.DChatMsg.MsgHead.equals(), org.gtdev.dchat.DChatMsg.MsgHead.getTo_uin(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.MsgHead(), org.gtdev.dchat.network.recvThread.run(), org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/DChatMsg/MsgHead.java