DChat: org.gtdev.dchat.network.recvThread Class Reference
org.gtdev.dchat.network.recvThread Class Reference
Public Member Functions
recvThread (ConnMgr.Connection s)
void run ()
NetPack PullPack () throws IOException
Private Attributes
ConnMgr.Connection peer
ConnMgr cm
Detailed Description
Definition at line 7 of file recvThread.java.
Constructor & Destructor Documentation
recvThread()
org.gtdev.dchat.network.recvThread.recvThread (ConnMgr.Connection s) inline
Definition at line 12 of file recvThread.java.
References org.gtdev.dchat.network.recvThread.cm, org.gtdev.dchat.network.ConnMgr.getInstance(), and org.gtdev.dchat.network.recvThread.peer.
Member Function Documentation
PullPack()
NetPack org.gtdev.dchat.network.recvThread.PullPack () throws IOException inline
Definition at line 64 of file recvThread.java.
References org.gtdev.dchat.network.NetPack.body, org.gtdev.dchat.network.NetPack.fromConnection, org.gtdev.dchat.network.NetPack.header, org.gtdev.dchat.network.recvThread.peer, and org.gtdev.dchat.network.NetPack.NetHeader.tail.
Referenced by org.gtdev.dchat.network.recvThread.run().
run()
void org.gtdev.dchat.network.recvThread.run () inline
Definition at line 18 of file recvThread.java.
References org.gtdev.dchat.network.recvThread.cm, org.gtdev.dchat.network.MsgPack.DealCmd(), org.gtdev.dchat.network.NetPack.fromConnection, org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.MsgPack.getNetPack(), org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.network.recvThread.peer, org.gtdev.dchat.network.recvThread.PullPack(), org.gtdev.dchat.network.ConnMgr.removePeer(), org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER, and org.gtdev.dchat.DChatMsg.MsgHead.to_uin.
Member Data Documentation
cm
ConnMgr org.gtdev.dchat.network.recvThread.cm private
Definition at line 10 of file recvThread.java.
Referenced by org.gtdev.dchat.network.recvThread.recvThread(), and org.gtdev.dchat.network.recvThread.run().
peer
ConnMgr.Connection org.gtdev.dchat.network.recvThread.peer private
Definition at line 9 of file recvThread.java.
Referenced by org.gtdev.dchat.network.recvThread.PullPack(), org.gtdev.dchat.network.recvThread.recvThread(), and org.gtdev.dchat.network.recvThread.run().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/recvThread.java