DChat: com.qq.tars.protocol.tars.TarsInputStream Class Reference
com.qq.tars.protocol.tars.TarsInputStream Class Reference
Classes
class HeadData
class TarsDecodeException
Public Member Functions
TarsInputStream ()
TarsInputStream (ByteBuffer bs)
TarsInputStream (byte[] bs)
TarsInputStream (byte[] bs, int pos)
void warp (byte[] bs)
void wrap (byte[] bs)
void readHead (HeadData hd)
int peakHead (HeadData hd)
boolean skipToTag (int tag)
void skipToStructEnd ()
boolean read (boolean b, int tag, boolean isRequire)
byte read (byte c, int tag, boolean isRequire)
short read (short n, int tag, boolean isRequire)
int read (int n, int tag, boolean isRequire)
long read (long n, int tag, boolean isRequire)
float read (float n, int tag, boolean isRequire)
double read (double n, int tag, boolean isRequire)
String readByteString (String s, int tag, boolean isRequire)
String read (String s, int tag, boolean isRequire)
String readString (int tag, boolean isRequire)
String [] read (String[] s, int tag, boolean isRequire)
Map< String, String > readStringMap (int tag, boolean isRequire)
List readList (int tag, boolean isRequire)
boolean [] read (boolean[] l, int tag, boolean isRequire)
byte [] read (byte[] l, int tag, boolean isRequire)
short [] read (short[] l, int tag, boolean isRequire)
int [] read (int[] l, int tag, boolean isRequire)
long [] read (long[] l, int tag, boolean isRequire)
float [] read (float[] l, int tag, boolean isRequire)
double [] read (double[] l, int tag, boolean isRequire)
TarsStructBase directRead (TarsStructBase o, int tag, boolean isRequire)
TarsStructBase read (TarsStructBase o, int tag, boolean isRequire)
TarsStructBase [] read (TarsStructBase[] o, int tag, boolean isRequire)
int setServerEncoding (String se)
ByteBuffer getBs ()
Static Public Member Functions
static int readHead (HeadData hd, ByteBuffer bb)
Protected Attributes
String sServerEncoding = "GBK"
Package Functions
public< K, V > HashMap< K, V > readMap (Map< K, V > m, int tag, boolean isRequire)
private< K, V > Map< K, V > readMap (Map< K, V > mr, Map< K, V > m, int tag, boolean isRequire)
public< T > T [] readArray (T[] l, int tag, boolean isRequire)
public< T > List< T > readArray (List< T > l, int tag, boolean isRequire)
private< T > T [] readArrayImpl (T mt, int tag, boolean isRequire)
public< T > Object read (T o, int tag, boolean isRequire)
Private Member Functions
void skip (int len)
void skipField ()
void skipField (byte type)
Private Attributes
ByteBuffer bs
Detailed Description
Definition at line 30 of file TarsInputStream.java.
Constructor & Destructor Documentation
TarsInputStream() [1/4]
com.qq.tars.protocol.tars.TarsInputStream.TarsInputStream () inline
Definition at line 53 of file TarsInputStream.java.
TarsInputStream() [2/4]
com.qq.tars.protocol.tars.TarsInputStream.TarsInputStream (ByteBuffer bs) inline
Definition at line 57 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
TarsInputStream() [3/4]
com.qq.tars.protocol.tars.TarsInputStream.TarsInputStream (byte [] bs) inline
Definition at line 61 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
TarsInputStream() [4/4]
com.qq.tars.protocol.tars.TarsInputStream.TarsInputStream (byte [] bs, int pos) inline
Definition at line 65 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
Member Function Documentation
directRead()
TarsStructBase com.qq.tars.protocol.tars.TarsInputStream.directRead (TarsStructBase o, int tag, boolean isRequire) inline
Definition at line 849 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.newInit(), com.qq.tars.protocol.tars.TarsStructBase.readFrom(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
getBs()
ByteBuffer com.qq.tars.protocol.tars.TarsInputStream.getBs () inline
Definition at line 948 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.display().
peakHead()
int com.qq.tars.protocol.tars.TarsInputStream.peakHead (HeadData hd) inline
Definition at line 93 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, and com.qq.tars.protocol.tars.TarsInputStream.readHead().
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display(), com.qq.tars.protocol.tars.TarsInputStream.readString(), and com.qq.tars.protocol.tars.TarsInputStream.skipToTag().
read() [1/19]
boolean com.qq.tars.protocol.tars.TarsInputStream.read (boolean b, int tag, boolean isRequire) inline
Definition at line 196 of file TarsInputStream.java.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl(), org.gtdev.dchat.DChatMsg.Msg.readFrom(), org.gtdev.dchat.DChatMsg.MsgHead.readFrom(), com.qq.tars.protocol.tars.TarsInputStream.readList(), com.qq.tars.protocol.tars.TarsInputStream.readMap(), com.qq.tars.protocol.tars.TarsInputStream.readString(), com.qq.tars.protocol.tars.TarsInputStream.readStringMap(), and com.qq.tars.protocol.tars.TarsInputStream.skipField().
read() [2/19]
byte com.qq.tars.protocol.tars.TarsInputStream.read (byte c, int tag, boolean isRequire) inline
Definition at line 201 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [3/19]
short com.qq.tars.protocol.tars.TarsInputStream.read (short n, int tag, boolean isRequire) inline
Definition at line 221 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [4/19]
int com.qq.tars.protocol.tars.TarsInputStream.read (int n, int tag, boolean isRequire) inline
Definition at line 244 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [5/19]
long com.qq.tars.protocol.tars.TarsInputStream.read (long n, int tag, boolean isRequire) inline
Definition at line 270 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [6/19]
float com.qq.tars.protocol.tars.TarsInputStream.read (float n, int tag, boolean isRequire) inline
Definition at line 299 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [7/19]
double com.qq.tars.protocol.tars.TarsInputStream.read (double n, int tag, boolean isRequire) inline
Definition at line 319 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
read() [8/19]
String com.qq.tars.protocol.tars.TarsInputStream.read (String s, int tag, boolean isRequire) inline
Definition at line 372 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.MAX_STRING_LENGTH, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.sServerEncoding, com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [9/19]
String [] com.qq.tars.protocol.tars.TarsInputStream.read (String [] s, int tag, boolean isRequire) inline
Definition at line 487 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readArray().
read() [10/19]
boolean [] com.qq.tars.protocol.tars.TarsInputStream.read (boolean [] l, int tag, boolean isRequire) inline
Definition at line 634 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [11/19]
byte [] com.qq.tars.protocol.tars.TarsInputStream.read (byte [] l, int tag, boolean isRequire) inline
Definition at line 657 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SIMPLE_LIST, com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [12/19]
short [] com.qq.tars.protocol.tars.TarsInputStream.read (short [] l, int tag, boolean isRequire) inline
Definition at line 692 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [13/19]
int [] com.qq.tars.protocol.tars.TarsInputStream.read (int [] l, int tag, boolean isRequire) inline
Definition at line 715 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [14/19]
long [] com.qq.tars.protocol.tars.TarsInputStream.read (long [] l, int tag, boolean isRequire) inline
Definition at line 738 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [15/19]
float [] com.qq.tars.protocol.tars.TarsInputStream.read (float [] l, int tag, boolean isRequire) inline
Definition at line 761 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [16/19]
double [] com.qq.tars.protocol.tars.TarsInputStream.read (double [] l, int tag, boolean isRequire) inline
Definition at line 784 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [17/19]
TarsStructBase com.qq.tars.protocol.tars.TarsInputStream.read (TarsStructBase o, int tag, boolean isRequire) inline
Definition at line 869 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.readFrom(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
read() [18/19]
TarsStructBase [] com.qq.tars.protocol.tars.TarsInputStream.read (TarsStructBase [] o, int tag, boolean isRequire) inline
Definition at line 889 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readArray().
read() [19/19]
public<T> Object com.qq.tars.protocol.tars.TarsInputStream.read (T o, int tag, boolean isRequire) inline package
Definition at line 894 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readArray(), com.qq.tars.protocol.tars.TarsInputStream.readMap(), and com.qq.tars.protocol.tars.TarsInputStream.readString().
readArray() [1/2]
public<T> T [] com.qq.tars.protocol.tars.TarsInputStream.readArray (T [] l, int tag, boolean isRequire) inline package
Definition at line 807 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl().
Referenced by com.qq.tars.protocol.tars.TarsInputStream.read().
readArray() [2/2]
public<T> List<T> com.qq.tars.protocol.tars.TarsInputStream.readArray (List< T > l, int tag, boolean isRequire) inline package
Definition at line 812 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl().
readArrayImpl()
private<T> T [] com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl (T mt, int tag, boolean isRequire) inline package
Definition at line 825 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.readArray().
readByteString()
String com.qq.tars.protocol.tars.TarsInputStream.readByteString (String s, int tag, boolean isRequire) inline
Definition at line 342 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.HexUtil.bytes2HexStr(), com.qq.tars.protocol.tars.TarsStructBase.MAX_STRING_LENGTH, com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
readHead() [1/2]
static int com.qq.tars.protocol.tars.TarsInputStream.readHead (HeadData hd, ByteBuffer bb) inline static
Definition at line 78 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.HeadData.tag, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.directRead(), org.gtdev.dchat.network.ProtoDisplayer.do_display(), com.qq.tars.protocol.tars.TarsInputStream.peakHead(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl(), com.qq.tars.protocol.tars.TarsInputStream.readByteString(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.readList(), com.qq.tars.protocol.tars.TarsInputStream.readMap(), com.qq.tars.protocol.tars.TarsInputStream.readString(), com.qq.tars.protocol.tars.TarsInputStream.readStringMap(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), and com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd().
readHead() [2/2]
void com.qq.tars.protocol.tars.TarsInputStream.readHead (HeadData hd) inline
Definition at line 89 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, and com.qq.tars.protocol.tars.TarsInputStream.readHead().
readList()
List com.qq.tars.protocol.tars.TarsInputStream.readList (int tag, boolean isRequire) inline
Definition at line 555 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsStructBase.readFrom(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsInputStream.skip(), com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
readMap() [1/2]
public<K, V> HashMap<K, V> com.qq.tars.protocol.tars.TarsInputStream.readMap (Map< K, V > m, int tag, boolean isRequire) inline package
Definition at line 516 of file TarsInputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.read().
readMap() [2/2]
private<K, V> Map<K, V> com.qq.tars.protocol.tars.TarsInputStream.readMap (Map< K, V > mr, Map< K, V > m, int tag, boolean isRequire) inline package
Definition at line 521 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
readString()
String com.qq.tars.protocol.tars.TarsInputStream.readString (int tag, boolean isRequire) inline
Definition at line 410 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsStructBase.MAX_STRING_LENGTH, com.qq.tars.protocol.tars.TarsInputStream.peakHead(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), com.qq.tars.protocol.tars.TarsInputStream.sServerEncoding, com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, com.qq.tars.protocol.tars.TarsInputStream.HeadData.tag, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.read(), org.gtdev.dchat.DChatMsg.Msg.readFrom(), org.gtdev.dchat.DChatMsg.MsgHead.readFrom(), and com.qq.tars.protocol.tars.TarsInputStream.readStringMap().
readStringMap()
Map<String, String> com.qq.tars.protocol.tars.TarsInputStream.readStringMap (int tag, boolean isRequire) inline
Definition at line 491 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.readString(), com.qq.tars.protocol.tars.TarsInputStream.skipToTag(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display().
setServerEncoding()
int com.qq.tars.protocol.tars.TarsInputStream.setServerEncoding (String se) inline
Definition at line 943 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.sServerEncoding.
skip()
void com.qq.tars.protocol.tars.TarsInputStream.skip (int len) inline private
Definition at line 97 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.readList(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), and com.qq.tars.protocol.tars.TarsInputStream.skipToTag().
skipField() [1/2]
void com.qq.tars.protocol.tars.TarsInputStream.skipField () inline private
Definition at line 127 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readHead(), and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.skipField(), com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), and com.qq.tars.protocol.tars.TarsInputStream.skipToTag().
skipField() [2/2]
void com.qq.tars.protocol.tars.TarsInputStream.skipField (byte type) inline private
Definition at line 133 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsStructBase.SIMPLE_LIST, com.qq.tars.protocol.tars.TarsInputStream.skip(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
skipToStructEnd()
void com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd () inline
Definition at line 119 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.directRead(), org.gtdev.dchat.network.ProtoDisplayer.do_display(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readList(), and com.qq.tars.protocol.tars.TarsInputStream.skipField().
skipToTag()
boolean com.qq.tars.protocol.tars.TarsInputStream.skipToTag (int tag) inline
Definition at line 101 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.peakHead(), com.qq.tars.protocol.tars.TarsInputStream.skip(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, com.qq.tars.protocol.tars.TarsInputStream.HeadData.tag, and com.qq.tars.protocol.tars.TarsInputStream.HeadData.type.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.directRead(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readArrayImpl(), com.qq.tars.protocol.tars.TarsInputStream.readByteString(), com.qq.tars.protocol.tars.TarsInputStream.readList(), com.qq.tars.protocol.tars.TarsInputStream.readMap(), com.qq.tars.protocol.tars.TarsInputStream.readString(), and com.qq.tars.protocol.tars.TarsInputStream.readStringMap().
warp()
void com.qq.tars.protocol.tars.TarsInputStream.warp (byte [] bs) inline
Definition at line 70 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs, and com.qq.tars.protocol.tars.TarsInputStream.wrap().
wrap()
void com.qq.tars.protocol.tars.TarsInputStream.wrap (byte [] bs) inline
Definition at line 74 of file TarsInputStream.java.
References com.qq.tars.protocol.tars.TarsInputStream.bs.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.warp().
Member Data Documentation
bs
ByteBuffer com.qq.tars.protocol.tars.TarsInputStream.bs private
Definition at line 40 of file TarsInputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.getBs(), com.qq.tars.protocol.tars.TarsInputStream.peakHead(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readByteString(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.readList(), com.qq.tars.protocol.tars.TarsInputStream.readString(), com.qq.tars.protocol.tars.TarsInputStream.skip(), com.qq.tars.protocol.tars.TarsInputStream.skipField(), com.qq.tars.protocol.tars.TarsInputStream.TarsInputStream(), com.qq.tars.protocol.tars.TarsInputStream.warp(), and com.qq.tars.protocol.tars.TarsInputStream.wrap().
sServerEncoding
String com.qq.tars.protocol.tars.TarsInputStream.sServerEncoding = "GBK" protected
Definition at line 941 of file TarsInputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readString(), and com.qq.tars.protocol.tars.TarsInputStream.setServerEncoding().
The documentation for this class was generated from the following file:
src/com/qq/tars/protocol/tars/TarsInputStream.java