DChat: org.gtdev.dchat.network.ProtoDisplayer Class Reference
org.gtdev.dchat.network.ProtoDisplayer Class Reference
Public Member Functions
ProtoDisplayer (StringBuilder sb, int level)
ProtoDisplayer (StringBuilder sb)
void display (TarsInputStream pis_)
String toString ()
Private Member Functions
void ps (int tag, String fieldName)
String getNamebyType (byte type)
boolean do_display ()
Private Attributes
StringBuilder sb
int _level = 0
TarsInputStream pis
Detailed Description
Definition at line 8 of file ProtoDisplayer.java.
Constructor & Destructor Documentation
ProtoDisplayer() [1/2]
org.gtdev.dchat.network.ProtoDisplayer.ProtoDisplayer (StringBuilder sb, int level) inline
Definition at line 20 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer.sb.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display().
ProtoDisplayer() [2/2]
org.gtdev.dchat.network.ProtoDisplayer.ProtoDisplayer (StringBuilder sb) inline
Definition at line 25 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer.sb.
Member Function Documentation
display()
void org.gtdev.dchat.network.ProtoDisplayer.display (TarsInputStream pis_) inline
Definition at line 29 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer.do_display(), com.qq.tars.protocol.tars.TarsInputStream.getBs(), and org.gtdev.dchat.network.ProtoDisplayer.pis.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display().
do_display()
boolean org.gtdev.dchat.network.ProtoDisplayer.do_display () inline private
Definition at line 71 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer._level, com.qq.tars.protocol.tars.TarsStructBase.BYTE, org.gtdev.dchat.network.ProtoDisplayer.display(), com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, org.gtdev.dchat.network.ProtoDisplayer.getNamebyType(), com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsInputStream.peakHead(), org.gtdev.dchat.network.ProtoDisplayer.pis, org.gtdev.dchat.network.ProtoDisplayer.ProtoDisplayer(), org.gtdev.dchat.network.ProtoDisplayer.ps(), com.qq.tars.protocol.tars.TarsInputStream.read(), com.qq.tars.protocol.tars.TarsInputStream.readHead(), com.qq.tars.protocol.tars.TarsInputStream.readStringMap(), org.gtdev.dchat.network.ProtoDisplayer.sb, com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsStructBase.SIMPLE_LIST, com.qq.tars.protocol.tars.TarsInputStream.skipToStructEnd(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, com.qq.tars.protocol.tars.TarsInputStream.HeadData.tag, com.qq.tars.protocol.tars.TarsInputStream.HeadData.type, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.display().
getNamebyType()
String org.gtdev.dchat.network.ProtoDisplayer.getNamebyType (byte type) inline private
Definition at line 37 of file ProtoDisplayer.java.
References com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsStructBase.SIMPLE_LIST, com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display().
ps()
void org.gtdev.dchat.network.ProtoDisplayer.ps (int tag, String fieldName) inline private
Definition at line 13 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer._level, and org.gtdev.dchat.network.ProtoDisplayer.sb.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display().
toString()
String org.gtdev.dchat.network.ProtoDisplayer.toString () inline
Definition at line 166 of file ProtoDisplayer.java.
References org.gtdev.dchat.network.ProtoDisplayer.sb.
Member Data Documentation
_level
int org.gtdev.dchat.network.ProtoDisplayer._level = 0 private
Definition at line 10 of file ProtoDisplayer.java.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display(), and org.gtdev.dchat.network.ProtoDisplayer.ps().
pis
TarsInputStream org.gtdev.dchat.network.ProtoDisplayer.pis private
Definition at line 11 of file ProtoDisplayer.java.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.display(), and org.gtdev.dchat.network.ProtoDisplayer.do_display().
sb
StringBuilder org.gtdev.dchat.network.ProtoDisplayer.sb private
Definition at line 9 of file ProtoDisplayer.java.
Referenced by org.gtdev.dchat.network.ProtoDisplayer.do_display(), org.gtdev.dchat.network.ProtoDisplayer.ProtoDisplayer(), org.gtdev.dchat.network.ProtoDisplayer.ps(), and org.gtdev.dchat.network.ProtoDisplayer.toString().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/ProtoDisplayer.java