DChat: com.qq.tars.protocol.tars.TarsOutputStream Class Reference
com.qq.tars.protocol.tars.TarsOutputStream Class Reference
Classes
class TarsEncodeException
Public Member Functions
TarsOutputStream (ByteBuffer bs)
TarsOutputStream (int capacity)
TarsOutputStream ()
ByteBuffer getByteBuffer ()
byte [] toByteArray ()
void reserve (int len)
void writeHead (byte type, int tag)
void write (boolean b, int tag)
void write (byte b, int tag)
void write (short n, int tag)
void write (int n, int tag)
void write (long n, int tag)
void write (float n, int tag)
void write (double n, int tag)
void writeStringByte (String s, int tag)
void writeByteString (String s, int tag)
void write (String s, int tag)
void write (boolean[] l, int tag)
void write (byte[] l, int tag)
void write (short[] l, int tag)
void write (int[] l, int tag)
void write (long[] l, int tag)
void write (float[] l, int tag)
void write (double[] l, int tag)
void write (TarsStructBase o, int tag)
void write (Byte o, int tag)
void write (Boolean o, int tag)
void write (Short o, int tag)
void write (Integer o, int tag)
void write (Long o, int tag)
void write (Float o, int tag)
void write (Double o, int tag)
void write (Object o, int tag)
int setServerEncoding (String se)
Protected Attributes
String sServerEncoding = "UTF-8"
Package Functions
public< K, V > void write (Map< K, V > m, int tag)
public< T > void write (T[] l, int tag)
public< T > void write (Collection< T > l, int tag)
Private Member Functions
void writeArray (Object[] l, int tag)
Private Attributes
ByteBuffer bs
Detailed Description
Definition at line 26 of file TarsOutputStream.java.
Constructor & Destructor Documentation
TarsOutputStream() [1/3]
com.qq.tars.protocol.tars.TarsOutputStream.TarsOutputStream (ByteBuffer bs) inline
Definition at line 37 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
TarsOutputStream() [2/3]
com.qq.tars.protocol.tars.TarsOutputStream.TarsOutputStream (int capacity) inline
Definition at line 41 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
TarsOutputStream() [3/3]
com.qq.tars.protocol.tars.TarsOutputStream.TarsOutputStream () inline
Definition at line 45 of file TarsOutputStream.java.
Member Function Documentation
getByteBuffer()
ByteBuffer com.qq.tars.protocol.tars.TarsOutputStream.getByteBuffer () inline
Definition at line 49 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
reserve()
void com.qq.tars.protocol.tars.TarsOutputStream.reserve (int len) inline
Definition at line 59 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.write(), com.qq.tars.protocol.tars.TarsOutputStream.writeArray(), com.qq.tars.protocol.tars.TarsOutputStream.writeByteString(), and com.qq.tars.protocol.tars.TarsOutputStream.writeStringByte().
setServerEncoding()
int com.qq.tars.protocol.tars.TarsOutputStream.setServerEncoding (String se) inline
Definition at line 360 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.sServerEncoding.
Referenced by com.qq.tars.protocol.tars.TarsStructBase.toByteArray().
toByteArray()
byte [] com.qq.tars.protocol.tars.TarsOutputStream.toByteArray () inline
Definition at line 53 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
Referenced by org.gtdev.dchat.network.MsgPack.getNetPack(), and com.qq.tars.protocol.tars.TarsStructBase.toByteArray().
write() [1/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (boolean b, int tag) inline
Definition at line 82 of file TarsOutputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.write(), com.qq.tars.protocol.tars.TarsOutputStream.writeArray(), org.gtdev.dchat.DChatMsg.Msg.writeTo(), and org.gtdev.dchat.DChatMsg.MsgHead.writeTo().
write() [2/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (byte b, int tag) inline
Definition at line 87 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.writeHead(), and com.qq.tars.protocol.tars.TarsStructBase.ZERO_TAG.
write() [3/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (short n, int tag) inline
Definition at line 97 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsStructBase.SHORT, com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [4/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (int n, int tag) inline
Definition at line 107 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.INT, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [5/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (long n, int tag) inline
Definition at line 117 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.LONG, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [6/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (float n, int tag) inline
Definition at line 127 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.FLOAT, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [7/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (double n, int tag) inline
Definition at line 133 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.DOUBLE, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [8/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (String s, int tag) inline
Definition at line 167 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.sServerEncoding, com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [9/27]
public<K, V> void com.qq.tars.protocol.tars.TarsOutputStream.write (Map< K, V > m, int tag) inline package
Definition at line 186 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.MAP, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [10/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (boolean [] l, int tag) inline
Definition at line 198 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [11/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (byte [] l, int tag) inline
Definition at line 206 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.TarsStructBase.BYTE, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsStructBase.SIMPLE_LIST, com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [12/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (short [] l, int tag) inline
Definition at line 214 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [13/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (int [] l, int tag) inline
Definition at line 222 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [14/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (long [] l, int tag) inline
Definition at line 230 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [15/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (float [] l, int tag) inline
Definition at line 238 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [16/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (double [] l, int tag) inline
Definition at line 246 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [17/27]
public<T> void com.qq.tars.protocol.tars.TarsOutputStream.write (T [] l, int tag) inline package
Definition at line 254 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.writeArray().
write() [18/27]
public<T> void com.qq.tars.protocol.tars.TarsOutputStream.write (Collection< T > l, int tag) inline package
Definition at line 266 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
write() [19/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (TarsStructBase o, int tag) inline
Definition at line 276 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsStructBase.STRUCT_BEGIN, com.qq.tars.protocol.tars.TarsStructBase.STRUCT_END, com.qq.tars.protocol.tars.TarsOutputStream.writeHead(), and com.qq.tars.protocol.tars.TarsStructBase.writeTo().
write() [20/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Byte o, int tag) inline
Definition at line 284 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [21/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Boolean o, int tag) inline
Definition at line 288 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [22/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Short o, int tag) inline
Definition at line 292 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [23/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Integer o, int tag) inline
Definition at line 296 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [24/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Long o, int tag) inline
Definition at line 300 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [25/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Float o, int tag) inline
Definition at line 304 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [26/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Double o, int tag) inline
Definition at line 308 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write().
write() [27/27]
void com.qq.tars.protocol.tars.TarsOutputStream.write (Object o, int tag) inline
Definition at line 312 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeArray().
writeArray()
void com.qq.tars.protocol.tars.TarsOutputStream.writeArray (Object [] l, int tag) inline private
Definition at line 258 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsStructBase.LIST, com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.write(), and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.write().
writeByteString()
void com.qq.tars.protocol.tars.TarsOutputStream.writeByteString (String s, int tag) inline
Definition at line 153 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.HexUtil.hexStr2Bytes(), com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
writeHead()
void com.qq.tars.protocol.tars.TarsOutputStream.writeHead (byte type, int tag) inline
Definition at line 69 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.write(), com.qq.tars.protocol.tars.TarsOutputStream.writeArray(), com.qq.tars.protocol.tars.TarsOutputStream.writeByteString(), and com.qq.tars.protocol.tars.TarsOutputStream.writeStringByte().
writeStringByte()
void com.qq.tars.protocol.tars.TarsOutputStream.writeStringByte (String s, int tag) inline
Definition at line 139 of file TarsOutputStream.java.
References com.qq.tars.protocol.tars.TarsOutputStream.bs, com.qq.tars.protocol.tars.HexUtil.hexStr2Bytes(), com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsStructBase.STRING1, com.qq.tars.protocol.tars.TarsStructBase.STRING4, and com.qq.tars.protocol.tars.TarsOutputStream.writeHead().
Member Data Documentation
bs
ByteBuffer com.qq.tars.protocol.tars.TarsOutputStream.bs private
Definition at line 35 of file TarsOutputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.getByteBuffer(), com.qq.tars.protocol.tars.TarsOutputStream.reserve(), com.qq.tars.protocol.tars.TarsOutputStream.TarsOutputStream(), com.qq.tars.protocol.tars.TarsOutputStream.toByteArray(), com.qq.tars.protocol.tars.TarsOutputStream.write(), com.qq.tars.protocol.tars.TarsOutputStream.writeByteString(), com.qq.tars.protocol.tars.TarsOutputStream.writeHead(), and com.qq.tars.protocol.tars.TarsOutputStream.writeStringByte().
sServerEncoding
String com.qq.tars.protocol.tars.TarsOutputStream.sServerEncoding = "UTF-8" protected
Definition at line 358 of file TarsOutputStream.java.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.setServerEncoding(), and com.qq.tars.protocol.tars.TarsOutputStream.write().
The documentation for this class was generated from the following file:
src/com/qq/tars/protocol/tars/TarsOutputStream.java