DChat: com.qq.tars.protocol.tars.TarsUtil Class Reference
com.qq.tars.protocol.tars.TarsUtil Class Reference
Static Public Member Functions
static boolean equals (boolean l, boolean r)
static boolean equals (byte l, byte r)
static boolean equals (char l, char r)
static boolean equals (short l, short r)
static boolean equals (int l, int r)
static boolean equals (long l, long r)
static boolean equals (float l, float r)
static boolean equals (double l, double r)
static boolean equals (Object l, Object r)
static int compareTo (boolean l, boolean r)
static int compareTo (byte l, byte r)
static int compareTo (char l, char r)
static int compareTo (short l, short r)
static int compareTo (int l, int r)
static int compareTo (long l, long r)
static int compareTo (float l, float r)
static int compareTo (double l, double r)
static< T extends Comparable< T > int compareTo (T l, T r)
static< T extends Comparable< T > int compareTo (List< T > l, List< T > r)
static< T extends Comparable< T > int compareTo (T[] l, T[] r)
static int compareTo (boolean[] l, boolean[] r)
static int compareTo (byte[] l, byte[] r)
static int compareTo (char[] l, char[] r)
static int compareTo (short[] l, short[] r)
static int compareTo (int[] l, int[] r)
static int compareTo (long[] l, long[] r)
static int compareTo (float[] l, float[] r)
static int compareTo (double[] l, double[] r)
static int hashCode (boolean o)
static int hashCode (boolean[] array)
static int hashCode (byte o)
static int hashCode (byte[] array)
static int hashCode (char o)
static int hashCode (char[] array)
static int hashCode (double o)
static int hashCode (double[] array)
static int hashCode (float o)
static int hashCode (float[] array)
static int hashCode (short o)
static int hashCode (short[] array)
static int hashCode (int o)
static int hashCode (int[] array)
static int hashCode (long o)
static int hashCode (long[] array)
static int hashCode (TarsStructBase[] array)
static int hashCode (Object object)
static byte [] getBufArray (ByteBuffer buffer)
static String getHexdump (byte[] array)
static String getHexdump (ByteBuffer in)
Static Package Functions
[static initializer]
Static Private Attributes
static final int iConstant = 37
static final int iTotal = 17
static final byte [] highDigits
static final byte [] lowDigits
Detailed Description
Definition at line 25 of file TarsUtil.java.
Member Function Documentation
[static initializer]()
com.qq.tars.protocol.tars.TarsUtil.[static initializer] () inline static package
compareTo() [1/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (boolean l, boolean r) inline static
Definition at line 67 of file TarsUtil.java.
Referenced by com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [2/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (byte l, byte r) inline static
Definition at line 71 of file TarsUtil.java.
compareTo() [3/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (char l, char r) inline static
Definition at line 75 of file TarsUtil.java.
compareTo() [4/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (short l, short r) inline static
Definition at line 79 of file TarsUtil.java.
compareTo() [5/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (int l, int r) inline static
Definition at line 83 of file TarsUtil.java.
compareTo() [6/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (long l, long r) inline static
Definition at line 87 of file TarsUtil.java.
compareTo() [7/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (float l, float r) inline static
Definition at line 91 of file TarsUtil.java.
compareTo() [8/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (double l, double r) inline static
Definition at line 95 of file TarsUtil.java.
compareTo() [9/19]
static <T extends Comparable<T> int com.qq.tars.protocol.tars.TarsUtil.compareTo (T l, T r) inline static
Definition at line 99 of file TarsUtil.java.
compareTo() [10/19]
static <T extends Comparable<T> int com.qq.tars.protocol.tars.TarsUtil.compareTo (List< T > l, List< T > r) inline static
Definition at line 103 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [11/19]
static <T extends Comparable<T> int com.qq.tars.protocol.tars.TarsUtil.compareTo (T [] l, T [] r) inline static
Definition at line 112 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [12/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (boolean [] l, boolean [] r) inline static
Definition at line 120 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [13/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (byte [] l, byte [] r) inline static
Definition at line 128 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [14/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (char [] l, char [] r) inline static
Definition at line 136 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [15/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (short [] l, short [] r) inline static
Definition at line 144 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [16/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (int [] l, int [] r) inline static
Definition at line 152 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [17/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (long [] l, long [] r) inline static
Definition at line 160 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [18/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (float [] l, float [] r) inline static
Definition at line 168 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
compareTo() [19/19]
static int com.qq.tars.protocol.tars.TarsUtil.compareTo (double [] l, double [] r) inline static
Definition at line 176 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.compareTo().
equals() [1/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (boolean l, boolean r) inline static
Definition at line 31 of file TarsUtil.java.
Referenced by org.gtdev.dchat.DChatMsg.Msg.equals(), and org.gtdev.dchat.DChatMsg.MsgHead.equals().
equals() [2/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (byte l, byte r) inline static
Definition at line 35 of file TarsUtil.java.
equals() [3/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (char l, char r) inline static
Definition at line 39 of file TarsUtil.java.
equals() [4/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (short l, short r) inline static
Definition at line 43 of file TarsUtil.java.
equals() [5/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (int l, int r) inline static
Definition at line 47 of file TarsUtil.java.
equals() [6/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (long l, long r) inline static
Definition at line 51 of file TarsUtil.java.
equals() [7/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (float l, float r) inline static
Definition at line 55 of file TarsUtil.java.
equals() [8/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (double l, double r) inline static
Definition at line 59 of file TarsUtil.java.
equals() [9/9]
static boolean com.qq.tars.protocol.tars.TarsUtil.equals (Object l, Object r) inline static
Definition at line 63 of file TarsUtil.java.
getBufArray()
static byte [] com.qq.tars.protocol.tars.TarsUtil.getBufArray (ByteBuffer buffer) inline static
Definition at line 358 of file TarsUtil.java.
getHexdump() [1/2]
static String com.qq.tars.protocol.tars.TarsUtil.getHexdump (byte [] array) inline static
Definition at line 384 of file TarsUtil.java.
getHexdump() [2/2]
static String com.qq.tars.protocol.tars.TarsUtil.getHexdump (ByteBuffer in) inline static
Definition at line 388 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.highDigits, and com.qq.tars.protocol.tars.TarsUtil.lowDigits.
hashCode() [1/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (boolean o) inline static
Definition at line 184 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
Referenced by org.gtdev.dchat.DChatMsg.Msg.hashCode(), org.gtdev.dchat.DChatMsg.MsgHead.hashCode(), and com.qq.tars.protocol.tars.TarsUtil.hashCode().
hashCode() [2/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (boolean [] array) inline static
Definition at line 188 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [3/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (byte o) inline static
Definition at line 200 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [4/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (byte [] array) inline static
Definition at line 204 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [5/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (char o) inline static
Definition at line 216 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [6/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (char [] array) inline static
Definition at line 220 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [7/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (double o) inline static
Definition at line 232 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.hashCode().
hashCode() [8/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (double [] array) inline static
Definition at line 236 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [9/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (float o) inline static
Definition at line 248 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [10/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (float [] array) inline static
Definition at line 252 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [11/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (short o) inline static
Definition at line 264 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [12/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (short [] array) inline static
Definition at line 268 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [13/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (int o) inline static
Definition at line 280 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [14/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (int [] array) inline static
Definition at line 284 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [15/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (long o) inline static
Definition at line 296 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [16/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (long [] array) inline static
Definition at line 300 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [17/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (TarsStructBase [] array) inline static
Definition at line 312 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
hashCode() [18/18]
static int com.qq.tars.protocol.tars.TarsUtil.hashCode (Object object) inline static
Definition at line 324 of file TarsUtil.java.
References com.qq.tars.protocol.tars.TarsUtil.hashCode(), com.qq.tars.protocol.tars.TarsUtil.iConstant, and com.qq.tars.protocol.tars.TarsUtil.iTotal.
Member Data Documentation
highDigits
final byte [] com.qq.tars.protocol.tars.TarsUtil.highDigits static private
Definition at line 364 of file TarsUtil.java.
Referenced by com.qq.tars.protocol.tars.TarsUtil.getHexdump().
iConstant
final int com.qq.tars.protocol.tars.TarsUtil.iConstant = 37 static private
Definition at line 27 of file TarsUtil.java.
Referenced by com.qq.tars.protocol.tars.TarsUtil.hashCode().
iTotal
final int com.qq.tars.protocol.tars.TarsUtil.iTotal = 17 static private
Definition at line 29 of file TarsUtil.java.
Referenced by com.qq.tars.protocol.tars.TarsUtil.hashCode().
lowDigits
final byte [] com.qq.tars.protocol.tars.TarsUtil.lowDigits static private
Definition at line 366 of file TarsUtil.java.
Referenced by com.qq.tars.protocol.tars.TarsUtil.getHexdump().
The documentation for this class was generated from the following file:
src/com/qq/tars/protocol/tars/TarsUtil.java