DChat: org.gtdev.dchat.network.functions.KICK Class Reference
org.gtdev.dchat.network.functions.KICK Class Reference
Public Member Functions
void feedMsg (MsgPack fm)
MsgPack reply ()
Package Attributes
MsgPack from
String reply
Detailed Description
Definition at line 11 of file KICK.java.
Member Function Documentation
feedMsg()
void org.gtdev.dchat.network.functions.KICK.feedMsg (MsgPack fm) inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 17 of file KICK.java.
References org.gtdev.dchat.network.ConnMgr.Connection.PeerType.CLIENT, org.gtdev.dchat.network.ConnMgr.doBroadcast(), org.gtdev.dchat.network.functions.KICK.from, org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.DChatMsg.MsgHead.getFrom_uin(), org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.network.ConnMgr.getPeer(), org.gtdev.dchat.network.ConnMgr.Connection.getSocket(), org.gtdev.dchat.DChatMsg.MsgType.KICK, org.gtdev.dchat.DChatMsg.Msg.msg_body, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_type, org.gtdev.dchat.client.MainUI.msgNotification(), org.gtdev.dchat.network.functions.KICK.reply(), org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.selfUIN, and org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER.
reply()
MsgPack org.gtdev.dchat.network.functions.KICK.reply () inline
Implements org.gtdev.dchat.network.SvcHandler.
Definition at line 48 of file KICK.java.
References org.gtdev.dchat.network.functions.KICK.from, org.gtdev.dchat.DChatMsg.MsgHead.from_uin, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getMessage(), org.gtdev.dchat.DChatMsg.MsgType.KICK, org.gtdev.dchat.DChatMsg.Msg.msg_head, org.gtdev.dchat.DChatMsg.MsgHead.msg_seq, org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.network.ConnMgr.Connection.PeerType.SERVER, org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type(), and org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin().
Referenced by org.gtdev.dchat.network.functions.KICK.feedMsg().
Member Data Documentation
from
MsgPack org.gtdev.dchat.network.functions.KICK.from package
Definition at line 13 of file KICK.java.
Referenced by org.gtdev.dchat.network.functions.KICK.feedMsg(), and org.gtdev.dchat.network.functions.KICK.reply().
reply
String org.gtdev.dchat.network.functions.KICK.reply package
Definition at line 14 of file KICK.java.
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/functions/KICK.java