DChat: org.gtdev.dchat.network.ConnMgr.Connection Class Reference
org.gtdev.dchat.network.ConnMgr.Connection Class Reference
Classes
enum PeerType
Public Member Functions
Connection (Socket s, PeerType peertype)
synchronized int getNextSeq ()
NetPack SendPack (NetPack b, int wait)
boolean CheckWaitingPack (NetPack p)
Socket getSocket ()
PeerType getPT ()
void addCmdHistory (String line)
ArrayList< String > getCmdHistory ()
Public Attributes
String peerUin = null
Package Attributes
Socket s
PeerType PT = PeerType.SERVER
Private Member Functions
NetPack PullPack (int TimeOut, int seq)
void DeleteFlag (int seq)
Private Attributes
final AtomicInteger seqFactory = new AtomicInteger(new Random().nextInt(100000))
Object LockWaitFlag = new Object()
Object LockReceive = new Object()
CopyOnWriteArrayList< Integer > mWaitFlagArr = new CopyOnWriteArrayList<Integer>()
CopyOnWriteArrayList< NetPack > mReceivePackQueue = new CopyOnWriteArrayList<NetPack>()
ArrayList< String > cmdHistory = new ArrayList<>()
Detailed Description
Definition at line 20 of file ConnMgr.java.
Constructor & Destructor Documentation
Connection()
org.gtdev.dchat.network.ConnMgr.Connection.Connection (Socket s, PeerType peertype) inline
Definition at line 30 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.s.
Member Function Documentation
addCmdHistory()
void org.gtdev.dchat.network.ConnMgr.Connection.addCmdHistory (String line) inline
Definition at line 122 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.cmdHistory.
CheckWaitingPack()
boolean org.gtdev.dchat.network.ConnMgr.Connection.CheckWaitingPack (NetPack p) inline
Definition at line 101 of file ConnMgr.java.
References org.gtdev.dchat.network.NetPack.header, org.gtdev.dchat.network.ConnMgr.Connection.LockReceive, org.gtdev.dchat.network.ConnMgr.Connection.mReceivePackQueue, org.gtdev.dchat.network.ConnMgr.Connection.mWaitFlagArr, and org.gtdev.dchat.network.NetPack.NetHeader.seq.
DeleteFlag()
void org.gtdev.dchat.network.ConnMgr.Connection.DeleteFlag (int seq) inline private
Definition at line 94 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.LockWaitFlag, and org.gtdev.dchat.network.ConnMgr.Connection.mWaitFlagArr.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.PullPack().
getCmdHistory()
ArrayList<String> org.gtdev.dchat.network.ConnMgr.Connection.getCmdHistory () inline
Definition at line 126 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.cmdHistory.
Referenced by org.gtdev.dchat.network.functions.STATS.reply().
getNextSeq()
synchronized int org.gtdev.dchat.network.ConnMgr.Connection.getNextSeq () inline
Definition at line 35 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.seqFactory.
getPT()
PeerType org.gtdev.dchat.network.ConnMgr.Connection.getPT () inline
Definition at line 120 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.PT.
getSocket()
Socket org.gtdev.dchat.network.ConnMgr.Connection.getSocket () inline
Definition at line 118 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.s.
Referenced by org.gtdev.dchat.network.functions.KICK.feedMsg().
PullPack()
NetPack org.gtdev.dchat.network.ConnMgr.Connection.PullPack (int TimeOut, int seq) inline private
Definition at line 73 of file ConnMgr.java.
References org.gtdev.dchat.network.ConnMgr.Connection.DeleteFlag(), org.gtdev.dchat.network.ConnMgr.Connection.LockReceive, and org.gtdev.dchat.network.ConnMgr.Connection.mReceivePackQueue.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.SendPack().
SendPack()
NetPack org.gtdev.dchat.network.ConnMgr.Connection.SendPack (NetPack b, int wait) inline
Definition at line 52 of file ConnMgr.java.
References org.gtdev.dchat.network.NetPack.getBytes(), org.gtdev.dchat.network.NetPack.header, org.gtdev.dchat.network.ConnMgr.Connection.LockWaitFlag, org.gtdev.dchat.network.ConnMgr.Connection.mWaitFlagArr, org.gtdev.dchat.network.ConnMgr.Connection.PullPack(), org.gtdev.dchat.network.ConnMgr.Connection.s, and org.gtdev.dchat.network.NetPack.NetHeader.seq.
Member Data Documentation
cmdHistory
ArrayList<String> org.gtdev.dchat.network.ConnMgr.Connection.cmdHistory = new ArrayList<>() private
Definition at line 50 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.addCmdHistory(), and org.gtdev.dchat.network.ConnMgr.Connection.getCmdHistory().
LockReceive
Object org.gtdev.dchat.network.ConnMgr.Connection.LockReceive = new Object() private
Definition at line 47 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.CheckWaitingPack(), and org.gtdev.dchat.network.ConnMgr.Connection.PullPack().
LockWaitFlag
Object org.gtdev.dchat.network.ConnMgr.Connection.LockWaitFlag = new Object() private
Definition at line 46 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.DeleteFlag(), and org.gtdev.dchat.network.ConnMgr.Connection.SendPack().
mReceivePackQueue
CopyOnWriteArrayList<NetPack> org.gtdev.dchat.network.ConnMgr.Connection.mReceivePackQueue = new CopyOnWriteArrayList<NetPack>() private
Definition at line 49 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.CheckWaitingPack(), and org.gtdev.dchat.network.ConnMgr.Connection.PullPack().
mWaitFlagArr
CopyOnWriteArrayList<Integer> org.gtdev.dchat.network.ConnMgr.Connection.mWaitFlagArr = new CopyOnWriteArrayList<Integer>() private
Definition at line 48 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.CheckWaitingPack(), org.gtdev.dchat.network.ConnMgr.Connection.DeleteFlag(), and org.gtdev.dchat.network.ConnMgr.Connection.SendPack().
peerUin
String org.gtdev.dchat.network.ConnMgr.Connection.peerUin = null
Definition at line 28 of file ConnMgr.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
PT
PeerType org.gtdev.dchat.network.ConnMgr.Connection.PT = PeerType.SERVER package
Definition at line 27 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.getPT().
s
Socket org.gtdev.dchat.network.ConnMgr.Connection.s package
Definition at line 26 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.Connection(), org.gtdev.dchat.network.ConnMgr.Connection.getSocket(), and org.gtdev.dchat.network.ConnMgr.Connection.SendPack().
seqFactory
final AtomicInteger org.gtdev.dchat.network.ConnMgr.Connection.seqFactory = new AtomicInteger(new Random().nextInt(100000)) private
Definition at line 29 of file ConnMgr.java.
Referenced by org.gtdev.dchat.network.ConnMgr.Connection.getNextSeq().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/network/ConnMgr.java