DChat: com.qq.tars.protocol.tars.HexUtil Class Reference
com.qq.tars.protocol.tars.HexUtil Class Reference
Static Public Member Functions
static String byte2HexStr (byte b)
static String bytes2HexStr (byte[] bytes)
static byte hexStr2Byte (String str)
static byte char2Byte (char ch)
static byte [] hexStr2Bytes (String str)
Static Public Attributes
static final byte [] emptybytes = new byte[0]
Static Private Attributes
static final char [] digits
Detailed Description
Definition at line 19 of file HexUtil.java.
Member Function Documentation
byte2HexStr()
static String com.qq.tars.protocol.tars.HexUtil.byte2HexStr (byte b) inline static
Definition at line 26 of file HexUtil.java.
References com.qq.tars.protocol.tars.HexUtil.digits.
bytes2HexStr()
static String com.qq.tars.protocol.tars.HexUtil.bytes2HexStr (byte [] bytes) inline static
Definition at line 34 of file HexUtil.java.
References com.qq.tars.protocol.tars.HexUtil.digits.
Referenced by com.qq.tars.protocol.tars.TarsInputStream.readByteString().
char2Byte()
static byte com.qq.tars.protocol.tars.HexUtil.char2Byte (char ch) inline static
Definition at line 57 of file HexUtil.java.
Referenced by com.qq.tars.protocol.tars.HexUtil.hexStr2Byte(), and com.qq.tars.protocol.tars.HexUtil.hexStr2Bytes().
hexStr2Byte()
static byte com.qq.tars.protocol.tars.HexUtil.hexStr2Byte (String str) inline static
Definition at line 49 of file HexUtil.java.
References com.qq.tars.protocol.tars.HexUtil.char2Byte().
hexStr2Bytes()
static byte [] com.qq.tars.protocol.tars.HexUtil.hexStr2Bytes (String str) inline static
Definition at line 69 of file HexUtil.java.
References com.qq.tars.protocol.tars.HexUtil.char2Byte(), and com.qq.tars.protocol.tars.HexUtil.emptybytes.
Referenced by com.qq.tars.protocol.tars.TarsOutputStream.writeByteString(), and com.qq.tars.protocol.tars.TarsOutputStream.writeStringByte().
Member Data Documentation
digits
final char [] com.qq.tars.protocol.tars.HexUtil.digits static private
Initial value:
= new char[] { '0', '1', '2', '3', '4',
            '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F' }
Definition at line 21 of file HexUtil.java.
Referenced by com.qq.tars.protocol.tars.HexUtil.byte2HexStr(), and com.qq.tars.protocol.tars.HexUtil.bytes2HexStr().
emptybytes
final byte [] com.qq.tars.protocol.tars.HexUtil.emptybytes = new byte[0] static
Definition at line 24 of file HexUtil.java.
Referenced by com.qq.tars.protocol.tars.HexUtil.hexStr2Bytes().
The documentation for this class was generated from the following file:
src/com/qq/tars/protocol/tars/HexUtil.java