DChat: org.gtdev.dchat.ParametersParser Class Reference
org.gtdev.dchat.ParametersParser Class Reference
Classes
class arg_handler
This is flag handler class to define a function to be called.
Static Public Member Functions
static void printHelp (arg_handler[] args)
static void procArgs (arg_handler[] defargs, String[] args)
Detailed Description
Definition at line 7 of file ParametersParser.java.
Member Function Documentation
printHelp()
static void org.gtdev.dchat.ParametersParser.printHelp (arg_handler [] args) inline static
Definition at line 35 of file ParametersParser.java.
Referenced by org.gtdev.dchat.ParametersParser.procArgs().
procArgs()
static void org.gtdev.dchat.ParametersParser.procArgs (arg_handler [] defargs, String [] args) inline static
Definition at line 43 of file ParametersParser.java.
References org.gtdev.dchat.ParametersParser.arg_handler.flag, org.gtdev.dchat.ParametersParser.arg_handler.handler.func(), org.gtdev.dchat.ParametersParser.arg_handler.Ifunc, and org.gtdev.dchat.ParametersParser.printHelp().
Referenced by org.gtdev.dchat.server.ServerLauncher.main(), and org.gtdev.dchat.client.ClientLauncher.main().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/ParametersParser.java