DChat: org.gtdev.dchat.client.ClientLauncher Class Reference
org.gtdev.dchat.client.ClientLauncher Class Reference
Static Public Member Functions
static void main (String[] args)
Static Package Functions
[static initializer]
Static Package Attributes
static String currentDir
static String server_addr = "::"
static String user_id = "newUser" + new Random().nextInt(1000)
static int server_port = 9055
static ParametersParser.arg_handler [] defargs
Detailed Description
Definition at line 15 of file ClientLauncher.java.
Member Function Documentation
[static initializer]()
org.gtdev.dchat.client.ClientLauncher.[static initializer] () inline static package
main()
static void org.gtdev.dchat.client.ClientLauncher.main (String [] args) inline static
Definition at line 53 of file ClientLauncher.java.
References org.gtdev.dchat.network.ConnMgr.addNewPeer(), org.gtdev.dchat.network.ConnMgr.Connection.PeerType.CLIENT, org.gtdev.dchat.client.ClientLauncher.defargs, org.gtdev.dchat.network.ConnMgr.getInstance(), org.gtdev.dchat.network.MsgPack.getNetPack(), org.gtdev.dchat.DChatMsg.MsgType.LOGIN, org.gtdev.dchat.network.ConnMgr.makeConnection(), org.gtdev.dchat.network.ConnMgr.Connection.peerUin, org.gtdev.dchat.ParametersParser.procArgs(), org.gtdev.dchat.network.ConnMgr.selfType, org.gtdev.dchat.network.ConnMgr.selfUIN, org.gtdev.dchat.client.ClientLauncher.server_addr, org.gtdev.dchat.client.ClientLauncher.server_port, org.gtdev.dchat.DChatMsg.MsgHead.setFrom_uin(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_seq(), org.gtdev.dchat.DChatMsg.MsgHead.setMsg_type(), org.gtdev.dchat.DChatMsg.MsgHead.setTo_uin(), and org.gtdev.dchat.client.ClientLauncher.user_id.
Member Data Documentation
currentDir
String org.gtdev.dchat.client.ClientLauncher.currentDir static package
Definition at line 17 of file ClientLauncher.java.
defargs
ParametersParser.arg_handler [] org.gtdev.dchat.client.ClientLauncher.defargs static package
Definition at line 19 of file ClientLauncher.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
server_addr
String org.gtdev.dchat.client.ClientLauncher.server_addr = "::" static package
Definition at line 17 of file ClientLauncher.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
server_port
int org.gtdev.dchat.client.ClientLauncher.server_port = 9055 static package
Definition at line 18 of file ClientLauncher.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
user_id
String org.gtdev.dchat.client.ClientLauncher.user_id = "newUser" + new Random().nextInt(1000) static package
Definition at line 17 of file ClientLauncher.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
The documentation for this class was generated from the following file:
src/org/gtdev/dchat/client/ClientLauncher.java