DChat: org.gtdev.dchat.DChatMsg.MsgType Enum Reference
org.gtdev.dchat.DChatMsg.MsgType Enum Reference
Public Member Functions
int value ()
String toString ()
Static Public Member Functions
static MsgType convert (int value)
Public Attributes
BROADCAST =(1)
STOP =(2)
LIST =(3)
KICK =(4)
STATS =(5)
LOGIN =(6)
Private Member Functions
MsgType (int value)
Private Attributes
final int value
Detailed Description
Definition at line 8 of file MsgType.java.
Constructor & Destructor Documentation
MsgType()
org.gtdev.dchat.DChatMsg.MsgType.MsgType (int value) inline private
Definition at line 19 of file MsgType.java.
Member Function Documentation
convert()
static MsgType org.gtdev.dchat.DChatMsg.MsgType.convert (int value) inline static
Definition at line 32 of file MsgType.java.
Referenced by org.gtdev.dchat.network.MsgPack.DealCmd().
toString()
String org.gtdev.dchat.DChatMsg.MsgType.toString () inline
Definition at line 28 of file MsgType.java.
value()
int org.gtdev.dchat.DChatMsg.MsgType.value () inline
Definition at line 23 of file MsgType.java.
Member Data Documentation
BROADCAST
org.gtdev.dchat.DChatMsg.MsgType.BROADCAST =(1)
Definition at line 10 of file MsgType.java.
Referenced by org.gtdev.dchat.network.functions.BROADCAST.feedMsg(), org.gtdev.dchat.network.functions.LOGIN.feedMsg(), and org.gtdev.dchat.client.MainUI.MainUI().
KICK
org.gtdev.dchat.DChatMsg.MsgType.KICK =(4)
Definition at line 13 of file MsgType.java.
Referenced by org.gtdev.dchat.network.functions.KICK.feedMsg(), org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.network.functions.KICK.reply().
LIST
org.gtdev.dchat.DChatMsg.MsgType.LIST =(3)
Definition at line 12 of file MsgType.java.
Referenced by org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.network.functions.LIST.reply().
LOGIN
org.gtdev.dchat.DChatMsg.MsgType.LOGIN =(6)
Definition at line 15 of file MsgType.java.
Referenced by org.gtdev.dchat.client.ClientLauncher.main().
STATS
org.gtdev.dchat.DChatMsg.MsgType.STATS =(5)
Definition at line 14 of file MsgType.java.
Referenced by org.gtdev.dchat.client.MainUI.MainUI(), and org.gtdev.dchat.network.functions.STATS.reply().
STOP
org.gtdev.dchat.DChatMsg.MsgType.STOP =(2)
Definition at line 11 of file MsgType.java.
Referenced by org.gtdev.dchat.network.functions.STOP.feedMsg(), and org.gtdev.dchat.client.MainUI.MainUI().
value
final int org.gtdev.dchat.DChatMsg.MsgType.value private
Definition at line 17 of file MsgType.java.
The documentation for this enum was generated from the following file:
src/org/gtdev/dchat/DChatMsg/MsgType.java