// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package org.gtdev.dchat.DChatMsg;

//import com.qq.tars.protocol.util.*;
//import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
//import com.qq.tars.protocol.tars.annotation.*;

////@TarsStruct
public class Msg {

	//@TarsStructProperty(order = 1, isRequire = true)
	public MsgHead msg_head = null;
	//@TarsStructProperty(order = 2, isRequire = true)
	public String msg_body = "";

	public MsgHead getMsg_head() {
		return msg_head;
	}

	public void setMsg_head(MsgHead msg_head) {
		this.msg_head = msg_head;
	}

	public String getMsg_body() {
		return msg_body;
	}

	public void setMsg_body(String msg_body) {
		this.msg_body = msg_body;
	}

	public Msg() {
	}

	public Msg(MsgHead msg_head, String msg_body) {
		this.msg_head = msg_head;
		this.msg_body = msg_body;
	}

	//@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(msg_head);
		result = prime * result + TarsUtil.hashCode(msg_body);
		return result;
	}

	//@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Msg)) {
			return false;
		}
		Msg other = (Msg) obj;
		return (
			TarsUtil.equals(msg_head, other.msg_head) &&
			TarsUtil.equals(msg_body, other.msg_body) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(msg_head, 1);
		_os.write(msg_body, 2);
	}

	static MsgHead cache_msg_head;
	static { 
		cache_msg_head = new MsgHead();
	}

	public void readFrom(TarsInputStream _is) {
		this.msg_head = (MsgHead) _is.read(cache_msg_head, 1, true);
		this.msg_body = _is.readString(2, true);
	}

}
